name: avs_hull_web
description: A Very Simple Hull editing program
publish_to: 'none'
version: 0.4.2

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  vector_math: ^2.0.0
  cupertino_icons: ^1.0.8
  xml: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - packages/cupertino_icons/assets/CupertinoIcons.ttf
